# Generated by Django 5.2.7 on 2025-11-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='subject',
            new_name='subject_code',
        ),
    ]
