# Generated by Django 5.2.7 on 2025-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_studentclassroom_student_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='ocr_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='ocr_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
