# Generated by Django 5.2.7 on 2025-12-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_studentassignment_extracted_text_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='generation_mode',
            field=models.CharField(blank=True, choices=[('manual', 'Manual Questions'), ('generated', 'AI Generated Questions')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='questions_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rag_collection',
            field=models.CharField(blank=True, help_text='ChromaDB collection name used for this assignment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rag_trained',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rag_trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['rag_collection'], name='classroom_a_rag_col_ab8116_idx'),
        ),
    ]
