# Generated by Django 5.2.7 on 2025-12-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_assignment_generation_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='generation_mode',
            field=models.CharField(blank=True, choices=[('uplaod', 'Upload Manual Questions'), ('generate', 'AI Generated Questions')], max_length=20, null=True),
        ),
    ]
