# Generated by Django 5.2.7 on 2025-12-26 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_assignment_generation_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='generation_mode',
            new_name='questionMethod',
        ),
    ]
