# Generated by Django 5.2.7 on 2026-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='correctness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
