# Generated by Django 5.2.7 on 2026-01-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_studentassignment_correctness_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='plagiarism_similarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
