# Generated by Django 5.2.7 on 2026-01-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_studentassignment_plagiarism_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='plagiarism_status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
