# Generated by Django 5.2.7 on 2026-02-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_studentassignment_plagiarism_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='marks',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='correctness_status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
