# Generated by Django 5.2.7 on 2025-10-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_delete_studnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('BLOCK', 'BLOCK'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('RE_APPLY', 'RE_APPLY')], default='PENDING', max_length=10),
        ),
    ]
