# Generated by Django 5.2.7 on 2025-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_approved_at_student_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='requested_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
