# Generated by Django 5.2.7 on 2025-10-27 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField()),
                ('middle_name', models.CharField(blank=True, null=True)),
                ('last_name', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7)),
                ('university', models.CharField()),
                ('phone_no', models.CharField(unique=True)),
                ('status', models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('BLOCK', 'BLOCK'), ('PENDING', 'PENDING')], max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
