# Generated by Django 5.2.7 on 2025-10-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_options_alter_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
