# Generated by Django 5.2.7 on 2025-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_college_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='point_of_contact',
            field=models.CharField(),
        ),
    ]
